In [2]:
import numpy as np
print(np.__version__)

2.4.2


In [4]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a
a.shape
a.ndim
a.dtype.name
a.itemsize
a.size
type(a)
b = np.array([6, 7, 8])
b
type(b)

numpy.ndarray

In [10]:
a = np.arange(6)                    # 1d array
print(a)

b = np.arange(12).reshape(4, 3)     # 2d array
print( b)

c = np.arange(24).reshape( 2,3,4)     # 3d array
print(c)

a[2]
b[2:3]

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[6, 7, 8]])

In [6]:
a = np.array = ([1,2,3,4])
b = np.arange (4)

c = a-b
b**2
10*np.sin(a)

array([ 8.41470985,  9.09297427,  1.41120008, -7.56802495])

In [7]:
a = np.array = ([1,2,3,4])
b = np.arange (4)
b

c = a-b
c

d = b-c
d

array([-1,  0,  1,  2])

In [ ]:

a = np.arange(15).reshape(3, 5)
a
a.shape
a.ndim
a.dtype.name
a.itemsize
a.size
type(a)
b = np.array([6, 7, 8])
b
type(b)

In [ ]:
a = np.arange(6)                    # 1d array
print(a)

b = np.arange(6).reshape(2, 3)     # 2d array
print( b)

c = np.arange(12).reshape(2,3,2)     # 3d array
print(c)

c.ndim


In [ ]:
b[2:2] # indexing

In [ ]:

c [0,:,:] # slicing

In [ ]:
c [-2,-1] # 2D se element ko acces krna

In [ ]:
c [1,-2,-1]  # 3D se element ko acces krna

In [ ]:
b  [0,0]=9
b

In [3]:

arr1D = np.arange(1, 7)  
print("1D Array:", arr1D)

print("Indexing arr1D[2]:", arr1D[2])        
print("Slicing arr1D[2:7]:", arr1D[2:5])    

arr2D = arr1D.reshape(2, 3)   
print("\nConverted 2D Array:\n", arr2D)

print("Element at [1,1]:", arr2D[1, 1])   

arr2D[1, 1] = 99
print("After replacing element at [1,1]:\n", arr2D)

arr1D_large = np.arange(1, 7)   
arr3D = arr1D_large.reshape(1, 3, 2)  
print("Converted 3D Array (1x3x2):", arr3D)

print("Element at [2,4,0]:", arr3D[0, 2, 1])  

arr1D_back = arr3D.flatten()
print("Converted back to 1D:", arr1D_back)

1D Array: [1 2 3 4 5 6]
Indexing arr1D[2]: 3
Slicing arr1D[2:7]: [3 4 5]

Converted 2D Array:
 [[1 2 3]
 [4 5 6]]
Element at [1,1]: 5
After replacing element at [1,1]:
 [[ 1  2  3]
 [ 4 99  6]]
Converted 3D Array (1x3x2): [[[1 2]
  [3 4]
  [5 6]]]
Element at [2,4,0]: 6
Converted back to 1D: [1 2 3 4 5 6]
